#!/usr/bin/env bash

BLUE="\033[36m"
BOLD="\033[1m"
NORMAL="\033[0m"

if [ "$1" == "templates_c" ]; then
  rm -f ../private/smarty/templates_c/*
elif [ "$1" == "cache" ]; then
  rm -f ../private/smarty/cache/*
else  # catches "--help", "-h", and "help" too
  echo -e "Usage: ./clear $BLUE<target>$NORMAL"
  echo
  echo -e "$BOLD"templates_c"$NORMAL"
  echo -e "  $BLUE"templates_c"$NORMAL\tClear Smarty's compiled templates."
  echo
  echo -e "$BOLD"cache"$NORMAL"
  echo -e "  $BLUE"cache"$NORMAL\t\tClear Smarty's cache."
  if [[ $1 == *"help"* ]] || [ "$1" == "" ]; then
    exit 0
  else
    exit 2
  fi
fi
